[package]
name = "rust"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
zmq = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.0"

[[bin]]
name = "main"
path = "src/main.rs"